Set config values for kanto
Signed-off-by: GitHub <noreply@github.com>

diff --git a/src/sh/sdv-kanto-ctl b/src/sh/sdv-kanto-ctl
--- a/src/sh/sdv-kanto-ctl
+++ b/src/sh/sdv-kanto-ctl
@@ -20,6 +20,7 @@
 
 #### Default config values ####
 VERBOSE=0
+RELOAD=1
 
 ### CONSTANTS below
 
@@ -85,13 +86,21 @@ display_help() {
 		echo "		-h or --hostname: Configure the hostname of the container registry (e.g. hub.docker.io, ghcr.io, ...)" 
 		echo "		-u or --username: Configure the username" 
 		echo "		-p or --password: Configure the password" 
-		echo "	remove-registry -h"
+		echo "	remove-registry -h <hostname>"
 		echo "		Removes the specified container registry"
 		echo "		-h or --hostname: The hostname of the container registry" 
 		echo "	remove-all-registries"
 		echo "		Removes all configured container registries"
+		echo "	list-registries"
+		echo "		Prints all configured container registries"
+		echo "	show-config"
+		echo "		Print the container management configuration"
+		echo "	set <key> <value>"
+		echo "		Set a primitive configuration value. Key in JSON Dot-Notation"
+		echo "		Examples: $0 set containers.registry_configurations.MyRegistry.credentials.password foobar"
+		echo "		          $0 set things.enable true"
 		echo "Options:"
-		echo "	--reload : Reload the configuration and restart the container-management service automatically"
+		echo "	--no-reload : Do not reload the configuration and restart the container-management service automatically"
 		echo "	--ansi : Don't use colored output."
 		echo "	--verbose | -v : Enable verbose mode."
 		echo "	--help : This message."
@@ -129,7 +138,11 @@ while [ -n "$1" ]; do
 			echo "Error: missing arguments for command add-registry"
 			echo "Usage:"
 			echo "	$0 add-registry -h <hostname> -u <username> -p <password>"
-			echo "	$0 --reload add-registry --hostname <hostname> --username <username> --password <password>"
+			echo "	$0 add-registry --hostname <hostname> --username <username> --password <password>"
+			echo ""
+			echo "Note: For GitHub Container Registry, you can use a Personal Access Token (PAT) as password."
+			echo "Example:"
+			echo " $0 add-registry -h ghcr.io -u github -p <YOUR_PAT>"
 			exit 1
 		fi
 	elif [ "$1" = "remove-registry" ]; then
@@ -161,9 +174,32 @@ while [ -n "$1" ]; do
 			echo "Error: Unknown argument for command remove-all-registries: $1"
 			exit 1
 		done
-
-	elif [ "$1" = "--reload" ] || [ "$1" = "-r" ]; then
-		RELOAD=1
+	elif [ "$1" = "list-registries" ]; then
+		COMMAND=$1
+		shift
+		while [ -n "$1" ]; do 
+			echo "Error: Unknown argument for command list-registries: $1"
+			exit 1
+		done
+	elif [ "$1" = "show-config" ]; then
+		COMMAND=$1
+		shift
+		while [ -n "$1" ]; do 
+			echo "Error: Unknown argument for command show-config: $1"
+			exit 1
+		done
+	elif [ "$1" = "set" ]; then
+		COMMAND=$1
+		CONFIG_KEY=$2
+		CONFIG_VALUE=$3
+		if [ "$#" -ne 3 ]; then
+			echo "ERROR: set command requires two arguments: <key> and <value>"
+			exit 1
+		else
+			shift 2
+		fi
+	elif [ "$1" = "--no-reload" ] || [ "$1" = "-r" ]; then
+		RELOAD=0
 	elif [ "$1" = "--verbose" ] || [ "$1" = "-v" ]; then
 		VERBOSE=1
 	elif [ "$1" = "--ansi" ]; then
@@ -227,8 +263,8 @@ add_registry() {
 
 	if [ -w ${KANTO_CONFIG} ]; then
 		if ! diff ${TMPFILE} ${KANTO_CONFIG} > /dev/null; then
-			BACKUP=$(mktemp )
-			[ "$VERBOSE" = "1" ] && echo "Backing up to ${BACKUP}"
+			BACKUP=$(mktemp --tmpdir kanto-cm-config-backup.XXXXXXX)
+			echo "Backing up to ${BACKUP}"
 			echo "Applying changes:"
 			cp ${KANTO_CONFIG} ${BACKUP}
 			cp ${TMPFILE} ${KANTO_CONFIG}
@@ -244,7 +280,7 @@ add_registry() {
 		echo "ERROR: No write permissions to ${KANTO_CONFIG}"
 		echo "The changes cannot be applied automatically, as the current user does not have write permissions to ${KANTO_CONFIG}"
 		echo "Either apply the configuration changes manually, or run this script with write permissions (e.g. use sudo):"
-		echo "	Run:  sudo cp ${TMPFILE} ${KANTO_CONFIG}"
+		echo "Run: sudo cp ${TMPFILE} ${KANTO_CONFIG}"
 		exit 1
 	fi
 }
@@ -261,8 +297,8 @@ remove_registry() {
 
 	if [ -w ${KANTO_CONFIG} ]; then
 		if ! diff ${TMPFILE} ${KANTO_CONFIG} > /dev/null; then
-			BACKUP=$(mktemp )
-			[ "$VERBOSE" = "1" ] && echo "Backing up to ${BACKUP}"
+			BACKUP=$(mktemp --tmpdir kanto-cm-config-backup.XXXXXXX)
+			echo "Backing up to ${BACKUP}"
 			echo "Applying changes:"
 			cp ${KANTO_CONFIG} ${BACKUP}
 			cp ${TMPFILE} ${KANTO_CONFIG}
@@ -278,7 +314,7 @@ remove_registry() {
 		echo "ERROR: No write permissions to ${KANTO_CONFIG}"
 		echo "The changes cannot be applied automatically, as the current user does not have write permissions to ${KANTO_CONFIG}"
 		echo "Either apply the configuration changes manually, or run this script with write permissions (e.g. use sudo):"
-		echo "	Run:  sudo cp ${TMPFILE} ${KANTO_CONFIG}"
+		echo "Run: sudo cp ${TMPFILE} ${KANTO_CONFIG}"
 		exit 1
 	fi
 }
@@ -295,8 +331,8 @@ remove_all_registries() {
 
 	if [ -w ${KANTO_CONFIG} ]; then
 		if ! diff ${TMPFILE} ${KANTO_CONFIG} > /dev/null; then
-			BACKUP=$(mktemp )
-			[ "$VERBOSE" = "1" ] && echo "Backing up to ${BACKUP}"
+			BACKUP=$(mktemp --tmpdir kanto-cm-config-backup.XXXXXXX)
+			echo "Backing up to ${BACKUP}"
 			echo "Applying changes:"
 			cp ${KANTO_CONFIG} ${BACKUP}
 			cp ${TMPFILE} ${KANTO_CONFIG}
@@ -312,9 +348,49 @@ remove_all_registries() {
 		echo "ERROR: No write permissions to ${KANTO_CONFIG}"
 		echo "The changes cannot be applied automatically, as the current user does not have write permissions to ${KANTO_CONFIG}"
 		echo "Either apply the configuration changes manually, or run this script with write permissions (e.g. use sudo):"
-		echo "	Run:  sudo cp ${TMPFILE} ${KANTO_CONFIG}"
+		echo "Run: sudo cp ${TMPFILE} ${KANTO_CONFIG}"
 		exit 1
 	fi
+}
+
+list_registries() {
+	jq '.containers.registry_configurations | keys[]' < ${KANTO_CONFIG}
+}
+
+show_config() {
+	jq < ${KANTO_CONFIG}
+}
+
+set_config() {
+	echo "Setting configuration $CONFIG_KEY to $CONFIG_VALUE"
+	TMPFILE=$(mktemp --tmpdir kanto-cm-config.XXXXXXX)
+	CONFIG_KEY=".${CONFIG_KEY}"
+	jq \
+	--arg CONFIG_KEY "$CONFIG_KEY" \
+	--arg CONFIG_VALUE "$CONFIG_VALUE" \
+	'setpath( $CONFIG_KEY|split(".")[1:]; $CONFIG_VALUE)' < ${KANTO_CONFIG} > ${TMPFILE}
+	[ "$VERBOSE" = "1" ] && echo "Created temp file for modifications: ${TMPFILE}"
+
+	if [ -w ${KANTO_CONFIG} ]; then
+		if ! diff ${TMPFILE} ${KANTO_CONFIG} > /dev/null; then
+			BACKUP=$(mktemp --tmpdir kanto-cm-config-backup.XXXXXXX)
+			echo "Backing up to ${BACKUP}"
+			cp ${KANTO_CONFIG} ${BACKUP}
+			cp ${TMPFILE} ${KANTO_CONFIG}
+			[ "$VERBOSE" = "1" ] &&	echo "Ok, changes applied."
+			CHANGES_APPLIED=1
+		else
+			echo "No difference to existing configuration."
+		fi
+	else
+		echo "ERROR: No write permissions to ${KANTO_CONFIG}"
+		jq < ${TMPFILE}
+		echo "The changes cannot be applied automatically, as the current user does not have write permissions to ${KANTO_CONFIG}"
+		echo "Either apply the configuration changes manually, or run this script with write permissions (e.g. use sudo):"
+		echo "Run: sudo cp ${TMPFILE} ${KANTO_CONFIG}"
+		exit 1
+	fi
+
 }
 
 ######################################################
@@ -329,17 +405,18 @@ fi
 [ "$COMMAND" = "add-registry" ] && add_registry
 [ "$COMMAND" = "remove-registry" ] && remove_registry
 [ "$COMMAND" = "remove-all-registries" ] && remove_all_registries
+[ "$COMMAND" = "list-registries" ] && list_registries
+[ "$COMMAND" = "show-config" ] && show_config
+[ "$COMMAND" = "set" ] && set_config
 
 if [ "$CHANGES_APPLIED" ]; then
 	if [ "${RELOAD}" ]; then
-		[ "$VERBOSE" = "1" ] &&	echo "Restarting Kanto Container-Management to apply changes..."
+		echo "Restarting Kanto Container-Management to apply changes..."
 		systemctl restart container-management
 		[ "$VERBOSE" = "1" ] &&	echo "Restart done."
 	else
 		echo "Note: Kanto requires a restart for the changes to take affect."
 	fi
-else
-	echo "Warning: No changes have been applied."
 fi
 
 exit 0
