Workflow test report
Signed-off-by: GitHub <noreply@github.com>

diff --git a/.github/workflows/build-leda-utils.yaml b/.github/workflows/build-leda-utils.yaml
--- a/.github/workflows/build-leda-utils.yaml
+++ b/.github/workflows/build-leda-utils.yaml
@@ -45,6 +45,13 @@ jobs:
       - name: Shell Tests
         run: |
           ./run-tests.sh
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Shell Tests            # Name of the check run which will be created
+          path: reports/report.xml    # Path to test results
+          reporter: jest-junit 
       - name: Debian Package Preparation
         run: |
           mkdir -p .debpkg/usr/bin
